<?php

namespace App\Back\Presenters;


use Nette;
use App\Model;


/**
 * Base presenter for all application presenters.
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter
{
  
  protected function beforeRender() {
    parent::beforeRender(); // TODO: Change the autogenerated stub
    $this->template->className = $this->getName();
  }

}
