<?php
  
  namespace App\Back\Presenters;
  
  use App\Back\Models\UserModel;
  use App\Traits\DatatableTrait;
  use Nette;
  
  /**
   * Class UserPresenter
   * Administration of users
   *
   * @author  Zdeněk Houdek
   * @created 04.04.2018
   */
  class UserPresenter extends BasePresenter
  {
    /** datatable extension for presenter*/
    use DatatableTrait;
    
    /** @var bool Do use Datatables plugin */
    protected $datatables = TRUE;
    /** @var UserModel */
    protected $model;
  
    /**
     * UserPresenter constructor.
     *
     * @param UserModel $model
     */
    public function __construct(UserModel $model) {
      $this->model = $model;
    }
    
    /**
     * Set up datatable properties
     *
     * @throws Nette\Application\UI\InvalidLinkException
     */
    protected function startup() {
      parent::startup(); // TODO: Change the autogenerated stub
      $this->setDTColumns([
        'Uživatelské jméno' => 'username',
        'Skupina'           => 'user_group.name',
        'Modul'             => ['column' => 'module.name', 'operator' => '=']
      ]);
      $this->setDTActions([
        'edit'   => [
          'button' => '<button title="Upravit uživatele" class="btn btn-theme-datatable btn-sm"><i class="fa fa-pencil"></i></button>',
          'action' => $this->link('edit')
        ],
        'delete' => [
          'button' => '<button title="Smazat uživatele" class="btn btn-theme-datatable btn-sm"><i class="fa fa-trash"></i></button>',
          'action' => $this->link('delete!')
        ]
      ]);
      $this->setDTButtons([
        'add' => [
          'class'  => 'btn btn-circle btn-theme',
          'title'  => 'Přidat uživatele',
          'text'   => 'Přidat uživatele',
          'action' => '',
          'icon'   => 'plus',
          'action' => $this->link('edit')
        ]
      ]);
    }
  
    /**
     * Edit/Add Action
     */
    public function actionEdit() {
      $id                    = $this->getParameter('rowId');
      $user                  = $this->model->getItemById($id);
      $this->template->title = $user ? "Editovat uživatele" : "Přidat uživatele";
      $this->template->user  = $user;
      $this->template->modal = FALSE;
      
      
      if ($this->isAjax()) {
        $this->template->modal  = TRUE;
        $this->payload->isModal = TRUE;
        $this->redrawControl('modal');
      }
    }
  
    /**
     * Delete action with prompt
     */
    public function handleDelete() {
      $this->actionDelete('Opravdu chcete smazat uživatele {USERNAME} ?',
        UserModel::_SUCCESS_DELETE_MESSAGE,
        UserModel::_FAIL_DELETE_MESSAGE);
    }
  }