<?php
  
  namespace App\Back\Presenters;
  
  use App\Back\Models\UserGroupModel;
  use App\Back\Models\UserModel;
  use App\Common\Components\Forms\BSForm;
  use App\Common\Models\ModuleModel;
  use App\Helpers\Strings;
  use App\Traits\DatatableTrait;
  use Nette;
  use Tracy\Dumper;

  /**
   * Class UserPresenter
   * Administration of users
   *
   * @author  Zdeněk Houdek
   * @created 04.04.2018
   */
  class UserPresenter extends BasePresenter
  {
    /** datatable extension for presenter*/
    use DatatableTrait;
    
    /** @var bool Do use Datatables plugin */
    protected $datatables = TRUE;
    
    /** @var UserModel */
    protected $model;
    
    /** @var UserGroupModel */
    protected $userGroupModel;
    
    /** @var ModuleModel */
    protected $moduleModel;
  
    /**
     * UserPresenter constructor.
     *
     * @param UserModel $model
     */
    public function __construct(UserModel $model, UserGroupModel $userGroupModel, ModuleModel $moduleModel) {
      $this->model = $model;
      $this->userGroupModel = $userGroupModel;
      $this->moduleModel = $moduleModel;
    }
    
    /**
     * Set up datatable properties
     *
     * @throws Nette\Application\UI\InvalidLinkException
     */
    protected function startup() {
      parent::startup(); // TODO: Change the autogenerated stub
      $this->setDTColumns([
        'Uživatelské jméno' => 'username',
        'Skupina'           => 'user_group.name',
        'Modul'             => ['column' => 'module.description', 'operator' => '=']
      ]);
      $this->setDTActions([
        'edit'   => [
          'button' => '<button title="Upravit uživatele" class="btn btn-theme-datatable btn-sm"><i class="fa fa-pencil"></i></button>',
          'action' => $this->link('edit')
        ],
        'delete' => [
          'button' => '<button title="Smazat uživatele" class="btn btn-theme-datatable btn-sm"><i class="fa fa-trash"></i></button>',
          'action' => $this->link('delete!')
        ]
      ]);
      $this->setDTButtons([
        'add' => [
          'class'  => 'btn btn-circle btn-theme',
          'title'  => 'Přidat uživatele',
          'text'   => 'Přidat uživatele',
          'action' => '',
          'icon'   => 'plus',
          'action' => $this->link('edit')
        ]
      ]);
    }
  
    /**
     * Edit/Add Action
     */
    public function actionEdit() {
      $id                    = $this->getParameter('rowId');
      $user                  = $this->model->getItemById($id);
      $this->template->title = $user ? "Editovat uživatele" : "Přidat uživatele";
      $this->template->user  = $user;
      $this->template->modal = FALSE;
  
      $this['userForm']->addSelect('user_group_id', 'Skupina', $this->userGroupModel->getPairsForSelect(
        'user_group_id',
        'name',
        FALSE));
      $this['userForm']->addSelect('module_id', 'Modul', $this->moduleModel->getPairsForSelect(
        'module_id',
        'description',
        FALSE,
        FALSE,
        ['display = ?' =>[1]]));
      if ($user) {
        $this['userForm']->setDefaults($user);
      }
      $this['userForm']->addSubmit('submit', 'Uložit');
      $this['userForm']->addButton('cancel', 'Zrušit')->setOmitted(TRUE);
      
      if ($this->isAjax()) {
        $this->template->modal  = TRUE;
        $this->payload->isModal = TRUE;
        $this->redrawControl('modal');
      }
    }
  
    /**
     * Delete action with prompt
     */
    public function handleDelete() {
      $this->actionDelete('Opravdu chcete smazat uživatele {USERNAME} ?',
        UserModel::_SUCCESS_DELETE_MESSAGE,
        UserModel::_FAIL_DELETE_MESSAGE);
    }
  
    /**
     * Edit/Add form
     *
     * @return BSForm
     */
    protected function createComponentUserForm() {
      $form = new BSForm();
      $form->isAjax();
      $form->addHidden('user_id');
      $form->addText('username', 'Uživatelské jméno')->setRequired('Musíte vyplnit uživatelské jméno');
      $form->onSuccess[] = [$this, 'userFormSubmit'];
      return $form;
    }
  
    /**
     *
     * Edit/Add form submited action
     *
     * @param Nette\Application\UI\Form $form
     * @param \stdClass                 $values
     *
     * @throws Nette\Application\AbortException
     */
    public function userFormSubmit(Nette\Application\UI\Form $form, \stdClass $values) {
      $values = array_map(function ($item) {
        return $item ? $item : NULL;
      }, (array)$values);
      try {
        $this->model->store($values);
      } catch (Nette\Database\UniqueConstraintViolationException $e) {
        $this->flashMessage(...Strings::placeholders($values, UserGroupModel::_FAIL_DUPLICITY_NAME_MESSAGE));
        $this->finishWithPayload();
      } catch (Exception $e) {
        $this->flashMessage(...Strings::placeholders($values, UserGroupModel::_FAIL_MESSAGE));
        $this->finishWithPayload(['closeModal' => TRUE]);
      }
      $this->flashMessage(...Strings::placeholders($values, UserGroupModel::_SUCCESS_MESSAGE));
      $this->finishWithPayload(['closeModal' => TRUE]);
    }
  }